<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HiraganaToUsageTypeSeeder extends Seeder
{
    public function run()
    {
        $mappings = [
            ['hiragana' => 'さ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'し', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'す', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'せ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'そ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'た', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ち', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'つ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'て', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'と', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'な', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'に', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ぬ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ね', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'の', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'は', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ひ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ふ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'へ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ほ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ま', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'み', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'む', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'め', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'も', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'や', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ゆ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ら', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'り', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'る', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'れ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'ろ', 'usage_type' => '自家用', 'vehicle_type' => '普通'],
            ['hiragana' => 'わ', 'usage_type' => 'レンタカー用', 'vehicle_type' => '普通'],
            ['hiragana' => 'れ', 'usage_type' => 'レンタカー用', 'vehicle_type' => '普通'],
            ['hiragana' => 'あ', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'い', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'う', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'え', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'か', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'き', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'く', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'け', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'こ', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'を', 'usage_type' => '事業用', 'vehicle_type' => '普通'],
            ['hiragana' => 'あ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'い', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'う', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'え', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'か', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'き', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'く', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'こ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'さ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'し', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'す', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'せ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'そ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'た', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ち', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'つ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'て', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'と', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'な', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'に', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ぬ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ね', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'の', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'は', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ひ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ふ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ほ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ま', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'み', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'む', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'め', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'も', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'や', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ゆ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'よ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ら', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'り', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'る', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'ろ', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'を', 'usage_type' => '自家用', 'vehicle_type' => '軽'],
            ['hiragana' => 'わ', 'usage_type' => 'レンタカー用', 'vehicle_type' => '軽'],
            ['hiragana' => 'り', 'usage_type' => '事業用', 'vehicle_type' => '軽'],
            ['hiragana' => 'れ', 'usage_type' => '事業用', 'vehicle_type' => '軽'],
        ];

        DB::table('hiragana_to_usage_type')->insert($mappings);
    }
}
