<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlateRegionToPrefectureSeeder extends Seeder
{
    public function run()
    {
        $regions = [
            ['region_name' => '札幌', 'prefecture_name' => '北海道'],
            ['region_name' => '函館', 'prefecture_name' => '北海道'],
            ['region_name' => '旭川', 'prefecture_name' => '北海道'],
            ['region_name' => '室蘭', 'prefecture_name' => '北海道'],
            ['region_name' => '苫小牧', 'prefecture_name' => '北海道'],
            ['region_name' => '釧路', 'prefecture_name' => '北海道'],
            ['region_name' => '知床', 'prefecture_name' => '北海道'],
            ['region_name' => '帯広', 'prefecture_name' => '北海道'],
            ['region_name' => '十勝', 'prefecture_name' => '北海道'],
            ['region_name' => '北見', 'prefecture_name' => '北海道'],
            ['region_name' => '青森', 'prefecture_name' => '青森県'],
            ['region_name' => '弘前', 'prefecture_name' => '青森県'],
            ['region_name' => '八戸', 'prefecture_name' => '青森県'],
            ['region_name' => '岩手', 'prefecture_name' => '岩手県'],
            ['region_name' => '盛岡', 'prefecture_name' => '岩手県'],
            ['region_name' => '平泉', 'prefecture_name' => '岩手県'],
            ['region_name' => '宮城', 'prefecture_name' => '宮城県'],
            ['region_name' => '仙台', 'prefecture_name' => '宮城県'],
            ['region_name' => '秋田', 'prefecture_name' => '秋田県'],
            ['region_name' => '山形', 'prefecture_name' => '山形県'],
            ['region_name' => '庄内', 'prefecture_name' => '山形県'],
            ['region_name' => '福島', 'prefecture_name' => '福島県'],
            ['region_name' => '会津', 'prefecture_name' => '福島県'],
            ['region_name' => '郡山', 'prefecture_name' => '福島県'],
            ['region_name' => '白河', 'prefecture_name' => '福島県'],
            ['region_name' => 'いわき', 'prefecture_name' => '福島県'],
            ['region_name' => '水戸', 'prefecture_name' => '茨城県'],
            ['region_name' => '土浦', 'prefecture_name' => '茨城県'],
            ['region_name' => 'つくば', 'prefecture_name' => '茨城県'],
            ['region_name' => '宇都宮', 'prefecture_name' => '栃木県'],
            ['region_name' => '日光', 'prefecture_name' => '栃木県'],
            ['region_name' => '那須', 'prefecture_name' => '栃木県'],
            ['region_name' => 'とちぎ', 'prefecture_name' => '栃木県'],
            ['region_name' => '群馬', 'prefecture_name' => '群馬県'],
            ['region_name' => '高崎', 'prefecture_name' => '群馬県'],
            ['region_name' => '前橋', 'prefecture_name' => '群馬県'],
            ['region_name' => '千葉', 'prefecture_name' => '千葉県'],
            ['region_name' => '成田', 'prefecture_name' => '千葉県'],
            ['region_name' => '野田', 'prefecture_name' => '千葉県'],
            ['region_name' => '柏', 'prefecture_name' => '千葉県'],
            ['region_name' => '松戸', 'prefecture_name' => '千葉県'],
            ['region_name' => '習志野', 'prefecture_name' => '千葉県'],
            ['region_name' => '船橋', 'prefecture_name' => '千葉県'],
            ['region_name' => '市川', 'prefecture_name' => '千葉県'],
            ['region_name' => '袖ヶ浦', 'prefecture_name' => '千葉県'],
            ['region_name' => '市原', 'prefecture_name' => '千葉県'],
            ['region_name' => '大宮', 'prefecture_name' => '埼玉県'],
            ['region_name' => '川口', 'prefecture_name' => '埼玉県'],
            ['region_name' => '熊谷', 'prefecture_name' => '埼玉県'],
            ['region_name' => '春日部', 'prefecture_name' => '埼玉県'],
            ['region_name' => '越谷', 'prefecture_name' => '埼玉県'],
            ['region_name' => '所沢', 'prefecture_name' => '埼玉県'],
            ['region_name' => '川越', 'prefecture_name' => '埼玉県'],
            ['region_name' => '品川', 'prefecture_name' => '東京都'],
            ['region_name' => '世田谷', 'prefecture_name' => '東京都'],
            ['region_name' => '足立', 'prefecture_name' => '東京都'],
            ['region_name' => '江東', 'prefecture_name' => '東京都'],
            ['region_name' => '葛飾', 'prefecture_name' => '東京都'],
            ['region_name' => '江戸川', 'prefecture_name' => '東京都'],
            ['region_name' => '練馬', 'prefecture_name' => '東京都'],
            ['region_name' => '杉並', 'prefecture_name' => '東京都'],
            ['region_name' => '板橋', 'prefecture_name' => '東京都'],
            ['region_name' => '多摩', 'prefecture_name' => '東京都'],
            ['region_name' => '八王子', 'prefecture_name' => '東京都'],
            ['region_name' => '横浜', 'prefecture_name' => '神奈川県'],
            ['region_name' => '川崎', 'prefecture_name' => '神奈川県'],
            ['region_name' => '相模', 'prefecture_name' => '神奈川県'],
            ['region_name' => '湘南', 'prefecture_name' => '神奈川県'],
            ['region_name' => '山梨', 'prefecture_name' => '山梨県'],
            ['region_name' => '新潟', 'prefecture_name' => '新潟県'],
            ['region_name' => '長岡', 'prefecture_name' => '新潟県'],
            ['region_name' => '上越', 'prefecture_name' => '新潟県'],
            ['region_name' => '長野', 'prefecture_name' => '長野県'],
            ['region_name' => '松本', 'prefecture_name' => '長野県'],
            ['region_name' => '諏訪', 'prefecture_name' => '長野県'],
            ['region_name' => '南信州', 'prefecture_name' => '長野県'],
            ['region_name' => '安曇野', 'prefecture_name' => '長野県'],
            ['region_name' => '富山', 'prefecture_name' => '富山県'],
            ['region_name' => '石川', 'prefecture_name' => '石川県'],
            ['region_name' => '金沢', 'prefecture_name' => '石川県'],
            ['region_name' => '名古屋', 'prefecture_name' => '愛知県'],
            ['region_name' => '三河', 'prefecture_name' => '愛知県'],
            ['region_name' => '岡崎', 'prefecture_name' => '愛知県'],
            ['region_name' => '豊田', 'prefecture_name' => '愛知県'],
            ['region_name' => '尾張小牧', 'prefecture_name' => '愛知県'],
            ['region_name' => '一宮', 'prefecture_name' => '愛知県'],
            ['region_name' => '春日井', 'prefecture_name' => '愛知県'],
            ['region_name' => '豊橋', 'prefecture_name' => '愛知県'],
            ['region_name' => '静岡', 'prefecture_name' => '静岡県'],
            ['region_name' => '沼津', 'prefecture_name' => '静岡県'],
            ['region_name' => '伊豆', 'prefecture_name' => '静岡県'],
            ['region_name' => '浜松', 'prefecture_name' => '静岡県'],
            ['region_name' => '岐阜', 'prefecture_name' => '岐阜県'],
            ['region_name' => '飛騨', 'prefecture_name' => '岐阜県'],
            ['region_name' => '三重', 'prefecture_name' => '三重県'],
            ['region_name' => '鈴鹿', 'prefecture_name' => '三重県'],
            ['region_name' => '四日市', 'prefecture_name' => '三重県'],
            ['region_name' => '伊勢志摩', 'prefecture_name' => '三重県'],
            ['region_name' => '福井', 'prefecture_name' => '福井県'],
            ['region_name' => '大阪', 'prefecture_name' => '大阪府'],
            ['region_name' => 'なにわ', 'prefecture_name' => '大阪府'],
            ['region_name' => '和泉', 'prefecture_name' => '大阪府'],
            ['region_name' => '堺', 'prefecture_name' => '大阪府'],
            ['region_name' => '京都', 'prefecture_name' => '京都府'],
            ['region_name' => '奈良', 'prefecture_name' => '奈良県'],
            ['region_name' => '飛鳥', 'prefecture_name' => '奈良県'],
            ['region_name' => '滋賀', 'prefecture_name' => '滋賀県'],
            ['region_name' => '和歌山', 'prefecture_name' => '和歌山県'],
            ['region_name' => '神戸', 'prefecture_name' => '兵庫県'],
            ['region_name' => '姫路', 'prefecture_name' => '兵庫県'],
            ['region_name' => '広島', 'prefecture_name' => '広島県'],
            ['region_name' => '福山', 'prefecture_name' => '広島県'],
            ['region_name' => '鳥取', 'prefecture_name' => '鳥取県'],
            ['region_name' => '島根', 'prefecture_name' => '島根県'],
            ['region_name' => '出雲', 'prefecture_name' => '島根県'],
            ['region_name' => '岡山', 'prefecture_name' => '岡山県'],
            ['region_name' => '倉敷', 'prefecture_name' => '岡山県'],
            ['region_name' => '山口', 'prefecture_name' => '山口県'],
            ['region_name' => '下関', 'prefecture_name' => '山口県'],
            ['region_name' => '徳島', 'prefecture_name' => '徳島県'],
            ['region_name' => '香川', 'prefecture_name' => '香川県'],
            ['region_name' => '高松', 'prefecture_name' => '香川県'],
            ['region_name' => '愛媛', 'prefecture_name' => '愛媛県'],
            ['region_name' => '高知', 'prefecture_name' => '高知県'],
            ['region_name' => '福岡', 'prefecture_name' => '福岡県'],
            ['region_name' => '北九州', 'prefecture_name' => '福岡県'],
            ['region_name' => '筑豊', 'prefecture_name' => '福岡県'],
            ['region_name' => '久留米', 'prefecture_name' => '福岡県'],
            ['region_name' => '佐賀', 'prefecture_name' => '佐賀県'],
            ['region_name' => '長崎', 'prefecture_name' => '長崎県'],
            ['region_name' => '佐世保', 'prefecture_name' => '長崎県'],
            ['region_name' => '熊本', 'prefecture_name' => '熊本県'],
            ['region_name' => '大分', 'prefecture_name' => '大分県'],
            ['region_name' => '宮崎', 'prefecture_name' => '宮崎県'],
            ['region_name' => '鹿児島', 'prefecture_name' => '鹿児島県'],
            ['region_name' => '奄美', 'prefecture_name' => '鹿児島県'],
            ['region_name' => '沖縄', 'prefecture_name' => '沖縄県'],
            ['region_name' => '富士山', 'prefecture_name' => '富士山ナンバー（静岡・山梨）'],
        ];

        DB::table('plate_region_to_prefecture')->insert($regions);
    }
}
