services:
  web:
    image: ghcr.io/kd-it/php-devcontainer/web:1748233351
    # build: docker/web
    volumes:
      - .:/app:cached
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    env_file:
      - ./.env
    depends_on:
      - app
      - db

  app:
    image: ghcr.io/kd-it/php-devcontainer/app:1748233351
    # build: docker/app
    env_file:
      - ./.env
    volumes:
      - .:/app:cached
      - vendor:/app/vendor
      - ./docker/app/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
  db:
    image: ghcr.io/densuke/mysql:main
    #build: db/build
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  python-api:
    build: ./python-service
    restart: unless-stopped
    env_file:
      - ./.env        # FastAPI 側でも環境変数を使いたい場合
    ports:
      - "127.0.0.1:8000:8000"   # 本番では外部公開しないなら削除
    volumes:
      - ./storage/app/videos:/data    # 動画ファイルを共有したいケース
volumes:
  db_data:
  vendor:
